# Foreign Greetings Package by Dhruv Ramu
matches:
# Afrikaans
  - trigger: ":afrikaanshello"
    replace: "hallo"
  - trigger: ":afrikaansbye"
    replace: "totsiens"
  - trigger: ":afrikaanshow"
    replace: "hoe gaan dit"
  - trigger: ":afrikaansgm"
    replace: "goeie more"
  - trigger: ":afrikaansgn"
    replace: "goeie nag"
  - trigger: ":afrikaansga"
    replace: "goeie middag"
  - trigger: ":afrikaansge"
    replace: "goeienaand"
  - trigger: ":afrikaansthx"
    replace: "dankie"

# Albanian
  - trigger: ":albanianhello"
    replace: "përshëndetje"
  - trigger: ":albanianbye"
    replace: "mirupafshim"
  - trigger: ":albanianhow"
    replace: "si jeni"
  - trigger: ":albaniangm"
    replace: "miremengjes"
  - trigger: ":albaniangn"
    replace: "naten e mire"
  - trigger: ":albanianga"
    replace: "mirembrema"
  - trigger: ":albaniange"
    replace: "mirembrema"
  - trigger: ":albanianthx"
    replace: "faleminderit"

# Amharic
  - trigger: ":amharichello"
    replace: "እው ሰላም ነው"
  - trigger: ":amharicbye"
    replace: "በህና ሁን"
  - trigger: ":amharichow"
    replace: "ስላም"
  - trigger: ":amharicgm"
    replace: "እንደምን አደርክ"
  - trigger: ":amharicgn"
    replace: "ደህና እደር"
  - trigger: ":amharicga"
    replace: "እንደምን አረፈድክ"
  - trigger: ":amharicge"
    replace: "አንደምን አመሸህ"
  - trigger: ":amharicthx"
    replace: "አመሰግናለሁ"


# Arabic
  - trigger: ":arabichello"
    replace: "أهلا"
  - trigger: ":arabicbye"
    replace: "وداعا"
  - trigger: ":arabichow"
    replace: "كيف حالك؟"
  - trigger: ":arabicgm"
    replace: "صباح الخير"
  - trigger: ":arabicgn"
    replace: "طاب مساؤك"
  - trigger: ":arabicga"
    replace: "طاب مسائك"
  - trigger: ":arabicge"
    replace: "مساء الخير"
  - trigger: ":arabicthx"
    replace: "شكرا لك"

# Armenian
  - trigger: ":armenianhello"
    replace: "Բարեւ Ձեզ"
  - trigger: ":armenianbye"
    replace: "ցտեսություն"
  - trigger: ":armenianhow"
    replace: "Ինչպես ես"
  - trigger: ":armeniangm"
    replace: "Բարի առավոտ"
  - trigger: ":armeniangn"
    replace: "Բարի գիշեր"
  - trigger: ":armenianga"
    replace: "Բարի օր"
  - trigger: ":armeniange"
    replace: "Բարի երեկո"
  - trigger: ":armenianthx"
    replace: "շնորհակալություն"

# Azerbaijani
  - trigger: ":azerbaijanihello"
    replace: "salam"
  - trigger: ":azerbaijanibye"
    replace: "sağol"
  - trigger: ":azerbaijanihow"
    replace: "necəsən"
  - trigger: ":azerbaijanigm"
    replace: "sabahınız xeyir"
  - trigger: ":azerbaijanign"
    replace: "gecəniz xeyrə"
  - trigger: ":azerbaijaniga"
    replace: "günortanız xeyir"
  - trigger: ":azerbaijanige"
    replace: "axşamınız xeyir"
  - trigger: ":azerbaijanithx"
    replace: "çox sağ ol"

# Belarusian
  - trigger: ":belarusianhello"
    replace: "добры дзень"
  - trigger: ":belarusianbye"
    replace: "да пабачэння"
  - trigger: ":belarusianhow"
    replace: "як ты"
  - trigger: ":belarusiangm"
    replace: "добрай раніцы"
  - trigger: ":belarusiangn"
    replace: "Дабранач"
  - trigger: ":belarusianga"
    replace: "добры дзень"
  - trigger: ":belarusiange"
    replace: "добры вечар"
  - trigger: ":belarusianthx"
    replace: "Дзякуй"

# Bengali
  - trigger: ":bengalihello"
    replace: "হ্যালো"
  - trigger: ":bengalibye"
    replace: "বিদায়"
  - trigger: ":bengalihow"
    replace: "আপনি কেমন আছেন"
  - trigger: ":bengaligm"
    replace: "সুপ্রভাত"
  - trigger: ":bengalign"
    replace: "শুভ রাত্রি"
  - trigger: ":bengaliga"
    replace: "শুভ অপরাহ্ন"
  - trigger: ":bengalige"
    replace: "শুভ সন্ধ্যা"
  - trigger: ":bengalithx"
    replace: "ধন্যবাদ"

# Bosnian
  - trigger: ":bosnianhello"
    replace: "zdravo"
  - trigger: ":bosnianbye"
    replace: "doviđenja"
  - trigger: ":bosnianhow"
    replace: "kako si"
  - trigger: ":bosniangm"
    replace: "dobro jutro"
  - trigger: ":bosniangn"
    replace: "laku noc"
  - trigger: ":bosnianga"
    replace: "dobar dan"
  - trigger: ":bosniange"
    replace: "Dobro veče"
  - trigger: ":bosnianthx"
    replace: "hvala ti"

# Bulgarian
  - trigger: ":bulgarianhello"
    replace: "Здравейте"
  - trigger: ":bulgarianbye"
    replace: "Довиждане"
  - trigger: ":bulgarianhow"
    replace: "Как сте"
  - trigger: ":bulgariangm"
    replace: "добро утро"
  - trigger: ":bulgariangn"
    replace: "лека нощ"
  - trigger: ":bulgarianga"
    replace: "добър ден"
  - trigger: ":bulgariange"
    replace: "добър вечер"
  - trigger: ":bulgarianthx"
    replace: "Благодаря ти"

# Chinese (Simplified)
  - trigger: ":chinesehello"
    replace: "你好"
  - trigger: ":chinesebye"
    replace: "再见"
  - trigger: ":chinesehow"
    replace: "你好吗"
  - trigger: ":chinesegm"
    replace: "上帝早上"
  - trigger: ":chinesegn"
    replace: "晚安"
  - trigger: ":chinesega"
    replace: "下午好"
  - trigger: ":chinesege"
    replace: "晚上好"
  - trigger: ":chinesethx"
    replace: "谢谢你"