# Foreign Greetings Package by Dhruv Ramu
matches:
# Random greetings (hello)
  - trigger: ":randomhello"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params: 
          choices:
            - "hallo"
            - "përshëndetje"
# Afrikaans
  - trigger: ":afrikaanshello"
    replace: "hallo"
  - trigger: ":afrikaansbye"
    replace: "totsiens"
  - trigger: ":afrikaanshow"
    replace: "hoe gaan dit"
  - trigger: ":afrikaansgm"
    replace: "goeie more"
  - trigger: ":afrikaansgn"
    replace: "goeie nag"
  - trigger: ":afrikaansga"
    replace: "goeie middag"
  - trigger: ":afrikaansge"
    replace: "goeienaand"
  - trigger: ":afrikaansthx"
    replace: "dankie"

# Albanian
  - trigger: ":albanianhello"
    replace: "përshëndetje"
  - trigger: ":albanianbye"
    replace: "mirupafshim"
  - trigger: ":albanianhow"
    replace: "si jeni"
  - trigger: ":albaniangm"
    replace: "miremengjes"
  - trigger: ":albaniangn"
    replace: "naten e mire"
  - trigger: ":albanianga"
    replace: "mirembrema"
  - trigger: ":albaniange"
    replace: "mirembrema"
  - trigger: ":albanianthx"
    replace: "faleminderit"

# Amharic
  - trigger: ":amharichello"
    replace: "እው ሰላም ነው"
  - trigger: ":amharicbye"
    replace: "በህና ሁን"
  - trigger: ":amharichow"
    replace: "ስላም"
  - trigger: ":amharicgm"
    replace: "እንደምን አደርክ"
  - trigger: ":amharicgn"
    replace: "ደህና እደር"
  - trigger: ":amharicga"
    replace: "እንደምን አረፈድክ"
  - trigger: ":amharicge"
    replace: "አንደምን አመሸህ"
  - trigger: ":amharicthx"
    replace: "አመሰግናለሁ"


# Arabic
  - trigger: ":arabichello"
    replace: "أهلا"
  - trigger: ":arabicbye"
    replace: "وداعا"
  - trigger: ":arabichow"
    replace: "كيف حالك؟"
  - trigger: ":arabicgm"
    replace: "صباح الخير"
  - trigger: ":arabicgn"
    replace: "طاب مساؤك"
  - trigger: ":arabicga"
    replace: "طاب مسائك"
  - trigger: ":arabicge"
    replace: "مساء الخير"
  - trigger: ":arabicthx"
    replace: "شكرا لك"

# Armenian
  - trigger: ":armenianhello"
    replace: "Բարեւ Ձեզ"
  - trigger: ":armenianbye"
    replace: "ցտեսություն"
  - trigger: ":armenianhow"
    replace: "Ինչպես ես"
  - trigger: ":armeniangm"
    replace: "Բարի առավոտ"
  - trigger: ":armeniangn"
    replace: "Բարի գիշեր"
  - trigger: ":armenianga"
    replace: "Բարի օր"
  - trigger: ":armeniange"
    replace: "Բարի երեկո"
  - trigger: ":armenianthx"
    replace: "շնորհակալություն"

# Azerbaijani
  - trigger: ":azerbaijanihello"
    replace: "salam"
  - trigger: ":azerbaijanibye"
    replace: "sağol"
  - trigger: ":azerbaijanihow"
    replace: "necəsən"
  - trigger: ":azerbaijanigm"
    replace: "sabahınız xeyir"
  - trigger: ":azerbaijanign"
    replace: "gecəniz xeyrə"
  - trigger: ":azerbaijaniga"
    replace: "günortanız xeyir"
  - trigger: ":azerbaijanige"
    replace: "axşamınız xeyir"
  - trigger: ":azerbaijanithx"
    replace: "çox sağ ol"

# Belarusian
  - trigger: ":belarusianhello"
    replace: "добры дзень"
  - trigger: ":belarusianbye"
    replace: "да пабачэння"
  - trigger: ":belarusianhow"
    replace: "як ты"
  - trigger: ":belarusiangm"
    replace: "добрай раніцы"
  - trigger: ":belarusiangn"
    replace: "Дабранач"
  - trigger: ":belarusianga"
    replace: "добры дзень"
  - trigger: ":belarusiange"
    replace: "добры вечар"
  - trigger: ":belarusianthx"
    replace: "Дзякуй"

# Bengali
  - trigger: ":bengalihello"
    replace: "হ্যালো"
  - trigger: ":bengalibye"
    replace: "বিদায়"
  - trigger: ":bengalihow"
    replace: "আপনি কেমন আছেন"
  - trigger: ":bengaligm"
    replace: "সুপ্রভাত"
  - trigger: ":bengalign"
    replace: "শুভ রাত্রি"
  - trigger: ":bengaliga"
    replace: "শুভ অপরাহ্ন"
  - trigger: ":bengalige"
    replace: "শুভ সন্ধ্যা"
  - trigger: ":bengalithx"
    replace: "ধন্যবাদ"

# Bosnian
  - trigger: ":bosnianhello"
    replace: "zdravo"
  - trigger: ":bosnianbye"
    replace: "doviđenja"
  - trigger: ":bosnianhow"
    replace: "kako si"
  - trigger: ":bosniangm"
    replace: "dobro jutro"
  - trigger: ":bosniangn"
    replace: "laku noc"
  - trigger: ":bosnianga"
    replace: "dobar dan"
  - trigger: ":bosniange"
    replace: "Dobro veče"
  - trigger: ":bosnianthx"
    replace: "hvala ti"

# Bulgarian
  - trigger: ":bulgarianhello"
    replace: "Здравейте"
  - trigger: ":bulgarianbye"
    replace: "Довиждане"
  - trigger: ":bulgarianhow"
    replace: "Как сте"
  - trigger: ":bulgariangm"
    replace: "добро утро"
  - trigger: ":bulgariangn"
    replace: "лека нощ"
  - trigger: ":bulgarianga"
    replace: "добър ден"
  - trigger: ":bulgariange"
    replace: "добър вечер"
  - trigger: ":bulgarianthx"
    replace: "Благодаря ти"

# Chinese (Simplified)
  - trigger: ":chinesehello"
    replace: "你好"
  - trigger: ":chinesebye"
    replace: "再见"
  - trigger: ":chinesehow"
    replace: "你好吗"
  - trigger: ":chinesegm"
    replace: "上帝早上"
  - trigger: ":chinesegn"
    replace: "晚安"
  - trigger: ":chinesega"
    replace: "下午好"
  - trigger: ":chinesege"
    replace: "晚上好"
  - trigger: ":chinesethx"
    replace: "谢谢你"

# Czech
  - trigger: ":czechhello"
    replace: "ahoj"
  - trigger: ":czechbye"
    replace: "rozloučení"
  - trigger: ":czechhow"
    replace: "jak se máte"
  - trigger: ":czechgm"
    replace: "dobré ráno"
  - trigger: ":czechgn"
    replace: "dobrou noc"
  - trigger: ":czechga"
    replace: "dobré odpoledne"
  - trigger: ":czechge"
    replace: "dobrý večer"
  - trigger: ":czechthx"
    replace: "děkuji"

# Danish
  - trigger: ":danishhello"
    replace: "hej"
  - trigger: ":danishbye"
    replace: "farvel"
  - trigger: ":danishhow"
    replace: "hvordan har du det"
  - trigger: ":danishgm"
    replace: "god morgen"
  - trigger: ":danishgn"
    replace: "godnat"
  - trigger: ":danishga"
    replace: "god eftermiddag"
  - trigger: ":danishge"
    replace: "god aften"
  - trigger: ":danishthx"
    replace: "tak skal du have"

# Dutch
  - trigger: ":dutchhello"
    replace: "hallo"
  - trigger: ":dutchbye"
    replace: "tot ziens"
  - trigger: ":dutchhow"
    replace: "hoe is het met je"
  - trigger: ":dutchgm"
    replace: "goedemorgen"
  - trigger: ":dutchgn"
    replace: "goedenacht"
  - trigger: ":dutchga"
    replace: "goedemiddag"
  - trigger: ":dutchge"
    replace: "goedeavond"
  - trigger: ":dutchthx"
    replace: "bedankt"

# Esperanto 😂
  - trigger: ":esperantohello"
    replace: "saluton"
  - trigger: ":esperantobye"
    replace: "adiaŭ"
  - trigger: ":esperantohow"
    replace: "kiel vi fartas"
  - trigger: ":esperantogm"
    replace: "bonan matenon"
  - trigger: ":esperantogn"
    replace: "bonan nokton"
  - trigger: ":esperantoga"
    replace: "bonan posttagmezon"
  - trigger: ":esperantoge"
    replace: "bonan vesperon"
  - trigger: ":esperantothx"
    replace: "dankon"

# Estonian
  - trigger: ":estonianhello"
    replace: "saluton"
  - trigger: ":estonianbye"
    replace: "hüvasti"
  - trigger: ":estonianhow"
    replace: "kuidas sul läheb"
  - trigger: ":estoniangm"
    replace: "tere hommikust"
  - trigger: ":estoniangn"
    replace: "head ööd"
  - trigger: ":estonianga"
    replace: "tere päevast"
  - trigger: ":estoniange"
    replace: "tere õhtust"
  - trigger: ":estonianthx"
    replace: "aitäh"

# Filipino
  - trigger: ":filipinohello"
    replace: "kamusta"
  - trigger: ":filipinobye"
    replace: "paalam"
  - trigger: ":filipinohow"
    replace: "kamusta ka"
  - trigger: ":filipinogm"
    replace: "magandang umaga"
  - trigger: ":filipinogn"
    replace: "magandang gabi"
  - trigger: ":filipinoga"
    replace: "magandang hapon"
  - trigger: ":filipinoge"
    replace: "magandang gabi"
  - trigger: ":filipinothx"
    replace: "salamat"

# Finnish
  - trigger: ":finnishhello"
    replace: "hei"
  - trigger: ":finnishbye"
    replace: "hyvästi"
  - trigger: ":finnishhow"
    replace: "mitä kuuluu"
  - trigger: ":finnishgm"
    replace: "hyvää huomenta"
  - trigger: ":finnishgn"
    replace: "hyvää yötä"
  - trigger: ":finnishga"
    replace: "hyvää iltapäivää"
  - trigger: ":finnishge"
    replace: "hyvää iltaa"
  - trigger: ":finnishthx"
    replace: "kiitos"

# French
  - trigger: ":frenchhello"
    replace: "bonjour"
  - trigger: ":frenchbye"
    replace: "au revoir"
  - trigger: ":frenchhow"
    replace: "Comment ça va"
  - trigger: ":frenchgm"
    replace: "bonjour"
  - trigger: ":frenchgn"
    replace: "bonne nuit"
  - trigger: ":frenchga"
    replace: "bonne après-midi"
  - trigger: ":frenchge"
    replace: "bonsoir"
  - trigger: ":frenchthx"
    replace: "merci"

# Georgian
  - trigger: ":georgianhello"
    replace: "გამარჯობა"
  - trigger: ":georgianbye"
    replace: "ნახვამდის"
  - trigger: ":georgianhow"
    replace: "როგორ ხარ"
  - trigger: ":georgiangm"
    replace: "დილა მშვიდობისა"
  - trigger: ":georgiangn"
    replace: "ღამე მშვიდობისა"
  - trigger: ":georgianga"
    replace: "შუადღემშვიდობის"
  - trigger: ":georgiange"
    replace: "საღამო მშვიდობისა"
  - trigger: ":georgianthx"
    replace: "გმადლობთ"

# German
  - trigger: ":germanhello"
    replace: "hallo"
  - trigger: ":germanbye"
    replace: "auf wiedersehen"
  - trigger: ":germanhow"
    replace: "wie gehts"
  - trigger: ":germangm"
    replace: "guten morgen"
  - trigger: ":germangn"
    replace: "gute nacht"
  - trigger: ":germanga"
    replace: "guten tag"
  - trigger: ":germange"
    replace: "guten abend"
  - trigger: ":germanthx"
    replace: "danke"

# Greek
  - trigger: ":greekhello"
    replace: "Χαίρετε"
  - trigger: ":greekbye"
    replace: "αντιο σας"
  - trigger: ":greekhow"
    replace: "Πώς είσαι"
  - trigger: ":greekgm"
    replace: "Καλημέρα"
  - trigger: ":greekgn"
    replace: "καληνυχτα"
  - trigger: ":greekga"
    replace: "καλό απόγευμα"
  - trigger: ":greekge"
    replace: "Καλό απόγευμα"
  - trigger: ":greekthx"
    replace: "ευχαριστώ"

# Hawaiian
  - trigger: ":hawaiianhello"
    replace: "aloha"
  - trigger: ":hawaiianbye"
    replace: "aloha"
  - trigger: ":hawaiianhow"
    replace: "pehea ʻoe"
  - trigger: ":hawaiiangm"
    replace: "aloha kakahiaka"
  - trigger: ":hawaiiangn"
    replace: "aloha ahiahi"
  - trigger: ":hawaiianga"
    replace: "aloha awakea, aloha auinalā"
  - trigger: ":hawaiiange"
    replace: "aloha ahiahi"
  - trigger: ":hawaiianthx"
    replace: "mahalo iā ʻoe"

# Hebrew
  - trigger: ":hebrewhello"
    replace: "שלום"
  - trigger: ":hebrewbye"
    replace: "הֱיה שלום"
  - trigger: ":hebrewhow"
    replace: "מה שלומך"
  - trigger: ":hebrewgm"
    replace: "בוקר טוב"
  - trigger: ":hebrewgn"
    replace: "לילה טוב"
  - trigger: ":hebrewga"
    replace: "אחר הצהריים טובים"
  - trigger: ":hebrewge"
    replace: "ערב טוב"
  - trigger: ":hebrewthx"
    replace: "תודה"

# Hindi
  - trigger: ":hindihello"
    replace: "नमस्ते"
  - trigger: ":hindibye"
    replace: "अलविदा"
  - trigger: ":hindihow"
    replace: "आप कैसे हैं"
  - trigger: ":hindigm"
    replace: "शुभ प्रभात"
  - trigger: ":hindign"
    replace: "शुभ रात्रि"
  - trigger: ":hindiga"
    replace: "नमस्कार"
  - trigger: ":hindige"
    replace: "सुसंध्या"
  - trigger: ":hindithx"
    replace: "धन्यवाद"


# Hungarian
  - trigger: ":hungarianhello"
    replace: "szia"
  - trigger: ":hungarianbye"
    replace: "viszontlátásra"
  - trigger: ":hungarianhow"
    replace: "hogy vagy"
  - trigger: ":hungariangm"
    replace: "शुभ प्रभात"
  - trigger: ":hungariangn"
    replace: "jó reggelt kívánok"
  - trigger: ":hungarianga"
    replace: "नमस्कार"
  - trigger: ":hungariange"
    replace: "सुसंध्या"
  - trigger: ":hungarianthx"
    replace: "धन्यवाद"